# Example config for vllm_runs_slurm.sh

MODEL_CONFIGS=(
  "meta-llama/Llama-3.1-8B-Instruct | bf16 | 1"
)

INPUT_LENS=(500 2500 5000 10000)
OUTPUT_LENS=(50 100 1500 5000)
CONCURRENCIES=(25 50 75)
NUM_PROMPTS=500
REPEATS=1
DATASET_NAME="random"
BACKEND="openai"

HOST="0.0.0.0"
PORT=8000
GPU_MEMORY_UTILIZATION=0.95
MAX_MODEL_LEN=""
EXTRA_SERVER_ARGS=""
EXTRA_BENCH_ARGS=""

CONTAINER_IMAGE="docker://rocm/vllm-dev:nightly_main_20260318"
CONTAINER_INSTANCE_NAME=""

BASE_OUT_DIR="./benchmark_results_slurm"
